---
title: "ENG 104: Pre-reading worksheet"
author: "Avinh Huynh"
date: "2023-09-05"
categories: [ENG104, HW]
---

###### [Link to assignment](https://sfsu.instructure.com/courses/27776/pages/homework-due-by-tuesday-september-5?module_item_id=1856592)

### Homework

-   [x] **Please send** me an email with proof of purchase of the required textbook, "A Pocket Style Manual (9th Edition)".

-   [ ] **Complete** a Pre-Reading Worksheet for each of the two articles.

-   [ ] **Read and annotate** the two articles (located in Class Resources).

-   [ ] **Write down** one **new thing** you can add to your daily routine that will add positive, or peaceful energy to your mind.

-   [ ] **Describe** how and why you think adding this one thing will create positive energy for you.

-   [ ] **If you are already** incorporating positive things into your everyday routine to add positive energy, please describe these and describe the effect these activities have on the way you feel.

### Notes

-   Please make sure you complete this homework before the start of our next Zoom class, as we will be using the results in our Zoom class on September 5.
-   I am not collecting this homework. The only thing you are submitting to me (by email) is your textbook proof of purchase. You are not submitting anything to Canvas this week.
