---
title: "ENG 104: Pre-reading worksheet"
author: "Avinh Huynh"
date: "2023-08-31"
categories: [ENG104, Week2, HW]
---

###### Due September 5th, 2023 (Tuesday)

###### [Link to assignment](https://sfsu.instructure.com/courses/27776/pages/homework-due-by-tuesday-september-5?module_item_id=1856592)

### Homework

-   [x] **Please send** me an email with proof of purchase of the required textbook, "A Pocket Style Manual (9th Edition)".

-   [x] **Complete** a Pre-Reading Worksheet for each of the two articles.

[Kübler-Ross "Five Stages of Grief" (1969) Pre-Reading Worksheet](https://docs.google.com/document/d/1w1BpBKCt9A3iGjxt19x9SU0ym5qe8hjqGqaFiE_5uKU/edit?usp=sharing)

["That Discomfort You’re Feeling Is Grief" Pre-Reading Worksheet](https://docs.google.com/document/d/1BNe7NzGSIfoW10hTivFBDTM-pzt8NaQsrSyLxBP1m0k/edit?usp=sharing)

-   [x] **Read and annotate** the two articles (located in Class Resources).

-   [x] **Write down** one **new thing** you can add to your daily routine that will add positive, or peaceful energy to your mind.

One thing I want to start doing consistently is drinking water every morning. I used to do this when I lived in San Diego, but after moving I haven't had the chance. Maybe I should buy a water bottle and refill it frequently, because then I wouldn't have to pay for plastic water bottles anymore and it would be cheaper.

-   [x] **Describe** how and why you think adding this one thing will create positive energy for you.

I think this would create positivity because water has many health benefits and also tastes very good. It can help me wake up in the morning, it will save money, and it will help the environment which SF I'm pretty sure is very environmentally proactive.

-   [x] **If you are already** incorporating positive things into your everyday routine to add positive energy, please describe these and describe the effect these activities have on the way you feel.

One thing I do to make my days more positive already is to keep myself as organized as possible with my meetings and appointments. I have been keeping my things in Google Calendar to remind me of my classes and obligations, so I can keep them all from overlapping.

### Notes

-   Please make sure you complete this homework before the start of our next Zoom class, as we will be using the results in our Zoom class on September 5.
-   I am not collecting this homework. The only thing you are submitting to me (by email) is your textbook proof of purchase. You are not submitting anything to Canvas this week.
