---
title: "ENG 104: Day 5 & 6 Homework (Week 3)"
author: "Avinh Huynh"
date: "2023-09-05"
categories: [ENG104, Week3, HW]
---

### Due by the start of class on Thursday, 9/7

-   **Have you ever** been puzzled or confused by something about essay writing, or writing in general? Now is your chance to find out answers to your questions!

I struggle a lot with the flow of a paper and proper grammatical structure. Whenever I read my girlfriend's papers (shes a very good writer), she writes like how she talks; but, when I write, I only know a few sentence structures and I don't know how to write how I think. When I think sentences in my head, there are run on sentences and improper sentences, so I don't know how to create my natural voice using proper grammar.

-   **Write down three things** that have confused you, or that you don't fully understand about essay writing (or reading), and have your list ready by the start of our class on Thursday.

###### - How to convey voice with proper grammar

###### - How to flow from the introduction to the background to the thesis

###### - How to have proper flow during the body paragraph to the topic sentences to the thesis

### Due by the start of class on Tuesday, 9/12

-   **Reflect** upon Elizabeth Kübler-Ross and David Kessler's articles, and on the cycle stress, grief, and behavior that Kessler discusses. Consider how adding positive things to your life every day could help to reduce stress levels, which in turn could reduce symptoms of grief, and positively affect our behavior and our life experience

-   **Make notes** of your reflections, as these will be useful to you for our next essay!
