---
title: "ENG 104: Day 5 (Week 3)"
author: "Avinh Huynh"
date: "2023-09-05"
categories: [ENG104, Week3]
---

### Story Time:

One upon a time, in a far far away land called the United Kingdom (or Britain I don't know the difference), Professor Drew Borland was a young leather-jacketed punk. At the prime age of 17, Professor Drew tried to buy a book or something using his checking account.

He didn't know if he had enough money in his account to buy the book, but he risked it and bought the book anyways. Unfortunately for Professor Drew, he did not have enough money in his checking account, and he ended up over drafting.

Expecting a lecture from the Banking Man, Professor Drew mentally braced himself. However, instead of a harsh lecturing, the bank man ended up telling him that the bank still wanted him because one day, Professor Drew would make money, and one day, he will deposit his money at that bank.

In the end, the Banking Man gave Professor Drew a loan to buy his books, and forgave Professor Drew for over drafting, which was a crime in the United Kingdom at the time. The Banking Man told him that, had Professor Drew spoken to the Bank Man sooner, he could have had a loan and not over drafted in the first place.

The moral of this story is, students should reach out to Professor Borland if they are struggling economically to buy **A Pocket Style Manual 9th Edition by Diana Hacker and Nancy Sommers**. Little do my classmates know, you can download an [online PDF here](https://knowdemia.com/download/a-pocket-style-manual-9th-edition-pdf-free/).

### Handkerchief Notes:

If you are trying to remember something, Professor Drew recommends setting constant alarms and snoozing them. Then, only after completing the thing, you can stop the alarm.

People in the olden days, in a far-far away land called the United Kingdom, people would knot their handkerchiefs to remember things. Then, they would grab their handkerchief and think, "What? Why is my handkerchief tied? Oh yeah! It's because I was supposed to do this!"

### What we did in class today

###### **Breakout Group 1**: 

With respect to the Covid pandemic, David Kessler interprets grief as "**the loss of normalcy**; \[e.g.\] the fear of economic toll, and the loss of connection". **Discuss** which aspects of a "loss of normalcy" **you can [personally]{.underline} identify with** and discuss how these and other aspects of the loss of normalcy have affected you since the start of the pandemic. **Make notes** of your findings.

###### **Breakout Group 2**: 

Kessler identifies "**anticipatory grief"** and defines this as "\[feelings of stress\] we get about what the future holds when we're uncertain". Discuss the aspects of "anticipatory grief" that **you** **can** [**personally**]{.underline} identify with since the start of the pandemic, and how these aspects of anticipatory grief **have affected [you]{.underline}**. **Make notes** of your findings.

###### **Breakout Group 3**: 

In the article **"[That Discomfort You're Feeling is Grief]{.underline}"**, David Kessler refers to Elizabeth Kübler-Ross's "[**Five Stages of Grief"**]{.underline}: **denial; anger; bargaining; sadness, and acceptance,** and Kessler proposes that the key to managing our stress lies within **acceptance.**

**1) Discuss** and make notes on the specific things you are already doing [**voluntarily**]{.underline} that involve acceptance of the Covid-19 crisis (e.g. hand washing, social distancing, avoiding crowds, getting vaccinated, taking classes online \[if this is not against your will\], being more patient with friends and family, etc.), and **discuss** what additional positive things you are doing that follow from your acceptance of the pandemic. **Make notes** of your findings.

**Note**: things you are being**forced to do *against your will*** do not count as acceptance (e.g. ***against your will*** having to move back home, give up your job, or move to online learning \[if this is against your will\], etc.). Acceptance only occurs when you do something by ***choice***, even though it may be unpleasant and unwelcome.

**2) Discuss** and make notes on whether you agree with Kessler that reducing our own stress comes from gaining control over our situations, and that acceptance is a vital aspect of this. Do you agree with him? **Make notes** of your findings.

###### **Breakout Group 4**: 

Kessler talks about the importance of finding "**a balance in the things you're thinking**". He suggests that we don't try to completely block out all of the painful images and fears we encounter, but he suggests instead we work to find ways to balance negative thoughts with **positive thoughts and images**.

**Discuss** and make notes on the following:

1.  Are **you** are consciously making time in your days to do things that are likely to **foster and create positive thoughts and images**?

2.  What techniques are **you** using now?

3.  What **positive-thinking** techniques could you use that you are not currently using?

4.  Can we **reduce** the negative images and thoughts we have, without trying to completely block them out? What **kinds of things** could we reduce, or cut back on in our lives in order to achieve this?

5.  Do you agree with David Kessler that we all **need to work hard** to find a way to balance the incessant flood of negative images and thoughts we all encounter, with more positive ones? 

### What I did Today

I was in group 3, and I said that we accepted COVID at the start because we liked not having to get ready for school and be judged for what we wear, but we rejected needing to show our cameras, some of us wearing masks, and one of us had mandated uniforms during Zoom.

We unanimously agreed that stress is proportional to the amount of control someone has over a situation. If you have a lot of control over a situation, it isn't as stressful. If you got into a car accident, but you had a lot of money, then you wouldn't be as stressed because you have control and know you can pay it off. If you didn't have enough money, then its stressful because you don't have as much control. Maybe you will have to get a loan, and what if you cant pay it off?

By this logic, acceptance of peril helps reduce stress because it gives you more control. If you accept that peril will happen, it gives you time to prepare and control the situation, and this reduces stress.
